Ft/contact
manzitresor/team4-website-project-real pull request #7
Opened 2024-05-30 09:49 UTC by albert-byiringiro

# Contact Section

This pull request implements the Contact page for the Baumeister website. The page includes a section section with imprint and disclaimer information.

## Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you Make sure you check every completed task. list them in this style

- [x] Create a responsive contact page layout for desktop, tablet, and mobile using TailwindCSS.
- [x] Implement the main section with imprint and disclaimer information.
- [x] Style the imprint and disclaimer sections for different screen sizes.
- [ ] ......

## Github board link (If appropriate/applicable)

Not Applicable

## Please check this Checklist before you submit your PR:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My code generates no warnings
- [x] There are no vulnerabilities

2024-05-30 10:38 UTC, manzitresor requested changes
Hi @albert-byiringiro and @Beccatoni 
You've done great work. Except small change you can make on space between items as it is in figma.

![ff](https://github.com/manzitresor/team4-website-project-real/assets/83731517/eac9921b-6076-45d3-8995-4536dde83e96)

2024-05-30 13:09 UTC, manzitresor approved these changes

2024-05-31 13:05 UTC, kareraolivier requested changes
Hey, you have done a great work so far.

I have added a few suggestions you can work on them

2024-05-31 15:52 UTC, albert-byiringiro commented on src/sections/contact.html
> +        accepts no liability for the content of these websites.
Implemented a clickable and page redirecting link: www.agentur-baumeister.com

2024-05-31 15:59 UTC, kareraolivier requested changes
Hello, there is one review you did not check.
so I updated it.
I explained more

2024-05-31 15:59 UTC, kareraolivier commented on src/sections/contact.html
> +    </div>
you map everything until here

2024-06-04 13:06 UTC, Beccatoni commented on src/sections/contact.html
> +    </div>
We have mapped everything as requested.

2024-06-04 13:21 UTC, albert-byiringiro commented on src/index.js
> +        ];
This is fixed.

2024-06-04 13:27 UTC, albert-byiringiro commented on src/index.js
> +
Removed as suggested

2024-06-04 13:29 UTC, albert-byiringiro commented on src/index.js
> +
This is resolved as highlighted.

2024-06-04 14:10 UTC, kareraolivier approved these changes
## This is great

2024-06-04 14:22 UTC, merged